### ISSUE TITLE
Assignment in forin causes an error

### ISSUE THREAD

**Issue by Marsup** [eslint/espree#128]
Using espree 2.0.1.

`espree.parse('for (var a = void 0 in obj) {}')`

gives

```
Error: Line 1: Unexpected token in
    at throwError (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:2069:17)
    at throwUnexpected (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:2124:9)
    at expect (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:2141:9)
    at parseForStatement (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:3862:13)
    at parseStatement (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:4255:44)
    at parseSourceElement (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:5116:24)
    at parseSourceElements (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:5154:25)
    at parseProgram (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:5174:12)
    at Object.parse (/workspace/backoffice/node_modules/lab/node_modules/espree/espree.js:5416:19)
    at repl:1:9
```
While it's obviously a dumb thing to do, this is the output I get from traceur 0.0.82 and it seems syntactically valid.
Upgrading to traceur 0.0.88 fixed this but I thought I'd let you know.

**Comment by nzakas** [comment]
As far as I know, assignment is not allowed in that location.

**Comment by Marsup** [comment]
Neither Firefox nor Chrome cries about it, I guess browsers are more permissive then.

**Comment by nzakas** [comment]
My understanding is that it was allowed in ES5 through a grammar bug and disallowed in ES6.

**Comment by Marsup** [comment]
Well, feel free to close the issue, I solved it by upgrading traceur anyway.
