### ISSUE TITLE
Error when parsing spread operator

### ISSUE THREAD

**Issue by yyx990803** [eslint/espree#129]
When parsing the following snippet with `ecmaFeatures: {spread: true}`:

``` js
function test (...args) {
  console.log(...args)
}
```

espree throws the following error:

```
/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:5428
        throw e;
              ^
Error: Line 1: Unexpected token ...
    at throwError (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:2069:17)
    at throwUnexpected (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:2132:5)
    at parseParam (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:4417:13)
    at parseParams (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:4482:18)
    at parseFunctionDeclaration (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:4533:15)
    at parseSourceElement (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:5103:24)
    at parseSourceElements (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:5154:25)
    at parseProgram (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:5174:12)
    at Object.parse (/Users/evan/Personal/semi/node_modules/eslint/node_modules/espree/espree.js:5416:19)
    at Object.<anonymous> (/Users/evan/Personal/semi/exp/parse.js:29:18)
```

**Comment by yyx990803** [comment]
FYI the same snippet works properly in ESLint when using the `babel-eslint` parser.

**Comment by nzakas** [comment]
You need to enable both `spread` and `restParams`

**Comment by yyx990803** [comment]
Ah, `restParams` doesn't seem to be in the doc: http://eslint.org/docs/user-guide/configuring

**Comment by yyx990803** [comment]
The error seems to persist even with both `spread` and `restParams` enabled.

**Comment by nzakas** [comment]
Those are the ESLint docs, the Espree readme mentions both:
https://github.com/eslint/espree

**Comment by yyx990803** [comment]
It does work correctly when both options are enabled - I was linting the wrong file!
