### ISSUE TITLE
`import { a } from "./b"` not parsed

### ISSUE THREAD

**Issue by mzgol** [eslint/espree#138]
The following ES6 module import construct:
```js
import { a } from "./b";
```

is not recognized by Espree. With file `ee.js`:
```js
var espree = require('espree');

var ast = espree.parse('import { a } from "./b"');
```
the output is:
```
$ node ee.js
/Users/mgol/_/node_modules/espree/espree.js:5435
        throw e;
              ^
Error: Line 1: Illegal import declaration
    at throwError (/Users/mgol/_/node_modules/espree/espree.js:2074:17)
    at throwErrorTolerant (/Users/mgol/_/node_modules/espree/espree.js:2086:20)
    at parseSourceElement (/Users/mgol/_/node_modules/espree/espree.js:5106:21)
    at parseSourceElements (/Users/mgol/_/node_modules/espree/espree.js:5161:25)
    at parseProgram (/Users/mgol/_/node_modules/espree/espree.js:5181:12)
    at Object.parse (/Users/mgol/_/node_modules/espree/espree.js:5423:19)
    at Object.<anonymous> (/Users/mgol/_/ee.js:3:18)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
```

**Comment by mzgol** [comment]
Ah, I didn't enable proper options. Never mind.
