### ISSUE TITLE
Object: Computed property setter getter parse failure

### ISSUE THREAD

**Issue by gyandeeps** [eslint/espree#139]
Using espree 2.0.2

If this is the code:

```js
var expr = 'foo';  var o = { set [expr](value) { val = value; }, get [expr]() { return val; } };
```

The espree parse throws an error:

```sh
$ node test.js
c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:5435
        throw e;
              ^
Error: Line 1: Unexpected token [
    at throwError (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:2069:17)
    at throwUnexpected (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:2132:5)
    at parseObjectPropertyKey (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:2349:5)
    at parseObjectProperty (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:2508:19)
    at parseObjectInitialiser (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:2697:20)
    at parsePrimaryExpression (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:2830:16)
    at parseLeftHandSideExpressionAllowCall (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:2974:57)
    at parsePostfixExpression (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:3023:12)
    at parseUnaryExpression (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:3083:16)
    at parseBinaryExpression (c:\Users\GS025879\Documents\webstrom\eslint\node_modules\espree\espree.js:3175:12)
```

Tried `esprima` online parser, it works fine.

**Comment by gyandeeps** [comment]
Forgot to turn on the ecmaFeature flag.
Got confused because `esprima` does it by default.
