### ISSUE TITLE
Rest Params and Arrow Functions Not working

### ISSUE THREAD

**Issue by xjamundx** [eslint/espree#187]
```
 require('./espree').parse('(a, ...b) => a[0]', {ecmaFeatures: { arrowFunctions: true, restParams: true }})
Error: Line 1: Unexpected token =>
    at throwError (/Users/jamuferguson/dev/espree/espree.js:2070:17)
    at throwUnexpected (/Users/jamuferguson/dev/espree/espree.js:2133:5)
    at reinterpretAsDestructuredParameter (/Users/jamuferguson/dev/espree/espree.js:3453:9)
    at reinterpretAsCoverFormalsList (/Users/jamuferguson/dev/espree/espree.js:3312:13)
    at parseAssignmentExpression (/Users/jamuferguson/dev/espree/espree.js:3534:22)
    at parseExpression (/Users/jamuferguson/dev/espree/espree.js:3568:16)
    at parseExpressionStatement (/Users/jamuferguson/dev/espree/espree.js:3763:16)
    at parseStatement (/Users/jamuferguson/dev/espree/espree.js:4290:44)
    at parseSourceElement (/Users/jamuferguson/dev/espree/espree.js:5176:16)
    at parseSourceElements (/Users/jamuferguson/dev/espree/espree.js:5209:25)
```

This is possibly related to #132 and was discovered while working on eslint/eslint#3353

**Comment by xjamundx** [comment]
Okay i'll work on this.

**Comment by xjamundx** [comment]
The issue here is that it's requiring `destructuring: true` in order to work. I'll figure it out!
