### ISSUE TITLE
Immediate invoked arrow function

### ISSUE THREAD

**Issue by kentor** [eslint/espree#205]
`() => {}()` does not parse in `espree`, but parses with `acorn`.

```js
const espree = require('espree');

espree.parse('() => {}()', {
  ecmaFeatures: {
    arrowFunctions: true,
  },
});
```

```
❯ node espree.js
/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:5495
        throw e;
              ^
Error: Line 1: Unexpected token (
    at throwError (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:2070:17)
    at throwUnexpected (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:2133:5)
    at consumeSemicolon (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:2214:9)
    at parseExpressionStatement (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:3770:5)
    at parseStatement (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:4301:44)
    at parseSourceElement (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:5187:16)
    at parseSourceElements (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:5220:25)
    at parseProgram (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:5240:12)
    at Object.parse (/Users/kenneth/stuff/eslint-test/node_modules/espree/espree.js:5483:19)
    at Object.<anonymous> (/Users/kenneth/stuff/eslint-test/espree.js:3:8)
```
I'm guessing hold off until the switch to acorn?

**Comment by nzakas** [comment]
I'm not sure, but this might actually be Syntax error. Need to double check.

**Comment by kentor** [comment]
Yeah it could be a Syntax error. In Chrome/Node it works, but in FF and MSEdge we get a Syntax Error, `missing ;`.

**Comment by nzakas** [comment]
@rwaldron any insights here?

**Comment by rwaldron** [comment]
@nzakas I'm actually not sure about this one. It looks like it should be valid, let's ask @bterlson

**Comment by bterlson** [comment]
Should not parse. An arrow function is an *AssignmentExpression* and a *CallExpression*'s LHS is basically a *MemberExpression* or another *CallExpression*. In order to immediately invoke an arrow function you have to wrap in parens, ala `(() => {})()`.

**Comment by nzakas** [comment]
Thanks @bterlson!

**Comment by rwaldron** [comment]
@bterlson excellent, that's what I was overlooking. Thanks!
