### ISSUE TITLE
object rest and destructured params

### ISSUE THREAD

**Issue by xjamundx** [eslint/espree#213]
We currently support:
`var {a, ...b} = c;`

But not:
`function b({a, ...b}) {}`

`babylon` and `babel-eslint` support that syntax instead per http://felix-kling.de/esprima_ast_explorer/ though acorn does not.

**Comment by xjamundx** [comment]
Rough stack trace
```
TypeError: Cannot read property 'type' of undefined at reinterpretAsDestructuredParameter (http://eslint.org/js/app/eslint.js:5674:13) at reinterpretAsDestructuredParameter (http://eslint.org/js/app/eslint.js:5681:13) at reinterpretAsCoverFormalsList (http://eslint.org/js/app/eslint.js:5512:13) at parseAssignmentExpression (http://eslint.org/js/app/eslint.js:5749:22) at parseExpression (http://eslint.org/js/app/eslint.js:5787:16) at parseExpressionStatement (http://eslint.org/js/app/eslint.js:5982:16) at parseStatement (http://eslint.org/js/app/eslint.js:6514:44) at parseSourceElement (http://eslint.org/js/app/eslint.js:7400:16) at parseSourceElements (http://eslint.org/js/app/eslint.js:7433:25) at parseProgram (http://eslint.org/js/app/eslint.js:7453:12)
```

**Comment by xjamundx** [comment]
From the `issue200` branch it works beautifully:

```
> require('./espree').parse('function x({a, ...b}) { }', { ecmaFeatures: { destructuring: true, experimentalObjectRestSpread: true}})
{ type: 'Program',
  body: 
   [ { type: 'FunctionDeclaration',
       id: [Object],
       generator: false,
       expression: false,
       params: [Object],
       body: [Object] } ],
  sourceType: 'script' }
```

**Comment by nzakas** [comment]
Working on this.
