### ISSUE TITLE
Regression: 3.0.0-alpha-2 and -3 'Unexpected token' is breaking eslint build

### ISSUE THREAD

**Issue by nre** [eslint/espree#224]
Input:
```
var espree = require("espree");

var DEFAULT_CONFIG = {
    ecmaFeatures: {
        blockBindings: true
    },
    comment: true,
    tokens: true,
    range: true,
    loc: true
};

espree.parse("let foo = bar;", DEFAULT_CONFIG);
```
The input works with v3.0.0-alpha-1 but fails with alpha-2 and -3:
```
C:\espree\node_modules\espree\espree.js:360
    throw err;
    ^

SyntaxError: Unexpected token foo
    at Parser.pp.raise (C:\espree\node_modules\espree\espree.js:356:15)
    at Parser.pp.unexpected (C:\espree\node_modules\espree\espree.js:389:10)
    at Parser.pp.semicolon (C:\espree\node_modules\espree\node_modules\acorn\dist\acorn.js:1479:73)
    at Parser.pp.parseExpressionStatement (:\espree\node_modules\espree\node_modules\acorn\dist\acorn.js:1969:8)
    at Parser.pp.parseStatement (C:\espree\node_modules\espree\node_modules\acorn\dist\acorn.js:1748:188)
    at Parser.pp.parseTopLevel (C:\espree\node_modules\espree\node_modules\acorn\dist\acorn.js:1663:21)
    at Parser.parse (C:\espree\node_modules\espree\node_modules\acorn\dist\acorn.js:1633:17)
    at Object.parse (C:\espree\node_modules\espree\node_modules\acorn\dist\acorn.js:902:44)
    at Object.parse (C:\espree\node_modules\espree\espree.js:663:21)
    at Object.<anonymous> (C:\espree\test.js:13:8)
```
This is breaking the eslint build: https://travis-ci.org/eslint/eslint/jobs/96264990

**Comment by gyandeeps** [comment]
Use this
```js
    parserOptions: {
        ecmaVersion: 6
    },
```

**Comment by nre** [comment]
Thanks. That solved this MWE in espree, but making the change in eslint/eslint/tests/lib/util/source-code.js#L24 caused `npm test` to spew 2 MB of assertion errors... I'll leave this issue to the maintainers.
