### ISSUE TITLE
espree Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by mysticatea** [eslint/espree#247]
I encountered a fatal error with the code: `({a, ...b} = {a, ...b})`.
This code can be parsed on espree@2, but cannot on espree@3.

```js
"use strict";

const espree = require("espree");
const ast = espree.parse(
    "({a, ...b} = {a, ...b})",
    {ecmaVersion: 6, ecmaFeatures: {experimentalObjectRestSpread: true}}
);

console.log("espree", JSON.stringify(ast, null, 4));
```

```
C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:1041
          if (prop.kind !== "init") this.raise(prop.key.start, "Object pattern can't contain getter or setter");
                                                       ^

TypeError: Cannot read property 'start' of undefined
    at Parser.pp.toAssignable (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:1041:56)
    at Parser.pp.parseMaybeAssign (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:116:58)
    at Parser.pp.parseParenAndDistinguishExpression (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:374:28)
    at Parser.pp.parseExprAtom (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:297:19)
    at Parser.pp.parseExprSubscripts (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:216:19)
    at Parser.pp.parseMaybeUnary (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:197:19)
    at Parser.pp.parseExprOps (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:110:19)
    at Parser.pp.parseExpression (C:\Users\t-nagashima.AD\Documents\GitHub\eslint\node_modules\acorn\dist\acorn.js:86:19)
```

**Comment by nzakas** [comment]
Thanks, I'll take a look.

**Comment by mysticatea** [comment]
Thank you!
