### ISSUE TITLE
espree may break acorn.

### ISSUE THREAD

**Issue by mysticatea** [eslint/espree#250]
```
$ npm install acorn@2.7 espree
$ node test.js
this would succeed
import espree
this would fail
TypeError: Cannot read property 'ecmaFeatures' of undefined
    at Parser.parseTopLevel (C:\Users\t-nagashima.AD\Documents\GitHub\sand2\node_modules\espree\espree.js:271:18)
    at Parser.parse (C:\Users\t-nagashima.AD\Documents\GitHub\sand2\node_modules\acorn\dist\acorn.js:1636:17)
    at parse (C:\Users\t-nagashima.AD\Documents\GitHub\sand2\node_modules\acorn\dist\acorn.js:905:44)
    at Object.<anonymous> (C:\Users\t-nagashima.AD\Documents\GitHub\sand2\test.js:17:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
```

**test.js**

```js
'use strict';

const aparse = require('acorn').parse;

//------------------------------------
console.log("this would succeed")
try {
    aparse('var foo = bar /*world*/;');  // Success!
} catch (e) {
    console.dir(e);
}

//------------------------------------
console.log("import espree")
require('espree');

//------------------------------------
console.log("this would fail")
try {
    aparse('var foo = bar /*world*/;');  // TypeError: Cannot read property 'ecmaFeatures' of undefined
} catch (e) {
    console.dir(e);
}
```

After `require('espree');`, acorn changes the behavior.
This might break tools which are using acorn (e.g. browserify).
Could espree override acorn's methods on an instance instead of the prototype? (similar to [acorn-jsx](https://github.com/RReverser/acorn-jsx/blob/master/inject.js#L359))

If accepted, I'm happy to work on this.

----

node v4.3.0
npm v3.5.0

**Comment by mysticatea** [comment]
https://gist.github.com/ukatama/44cd29fbd67a315b12f9

@ukatama has created a broken case of gulp + browserify + eslint.
Thank you very much!

**Comment by nzakas** [comment]
Yikes, that's not good. Definitely appreciate a patch!

**Comment by yyx990803** [comment]
Just ran into this today - Jade is breaking because it depends on a module which in turn depends on Acorn (which is monkey-patched by espree), would appreciate a quick release :)
