### ISSUE TITLE
"Unexpected token <methodname>" for an async method definition

### ISSUE THREAD

**Issue by andreaswachowski** [eslint/espree#297]
I stumbled upon the following using eslint (then narrowed it down to the parser):

*Setup:*

```
$ node --version
v6.6.0
$ npm i espree --save
[...]/espree
└─┬ espree@3.3.1
  ├── acorn@4.0.3
  └─┬ acorn-jsx@3.0.1
    └── acorn@3.3.0
```

(Note: The fix from eslint/espree#295 is already included here.)

*Test:*

The following file (say `async_method_test.js`)

```
var espree = require("espree");

var ast = espree.parse(`var SomeObject = {
    async someMethod() {
    }
}`, { ecmaVersion: 7 });
```

outputs `Unexpected token someMethod`. I would expect a successful parse instead.

```
$ node async_method_test.js
[...]/espree/node_modules/espree/espree.js:410
        throw err;
        ^

SyntaxError: Unexpected token someMethod
    at Parser.instance.raise.instance.raiseRecoverable ([...]/espree/node_modules/espree/espree.js:406:19)
    at Parser.instance.unexpected ([...]/espree/node_modules/espree/espree.js:439:14)
    at Parser.pp.expect ([...]/espree/node_modules/acorn/dist/acorn.js:610:28)
    at Parser.instance.parseObj ([...]/espree/node_modules/espree/espree.js:331:22)
    at Parser.pp$3.parseExprAtom ([...]/espree/node_modules/acorn/dist/acorn.js:1946:19)
    at Parser.pp$3.parseExprSubscripts ([...]/espree/node_modules/acorn/dist/acorn.js:1831:21)
    at Parser.pp$3.parseMaybeUnary ([...]/espree/node_modules/acorn/dist/acorn.js:1808:19)
    at Parser.pp$3.parseExprOps ([...]/espree/node_modules/acorn/dist/acorn.js:1750:21)
    at Parser.pp$3.parseMaybeConditional ([...]/espree/node_modules/acorn/dist/acorn.js:1733:21)
    at Parser.pp$3.parseMaybeAssign ([...]/espree/node_modules/acorn/dist/acorn.js:1710:21)
```

The "AsyncMethod" production in [the async/await spec](https://tc39.github.io/ecmascript-asyncawait/#prod-AsyncMethod) leads me to believe that the example should be valid. Having said that, apologies in advance in case I missed something obvious, I am not an expert on new JavaScript features (or parsers).

**Comment by platinumazure** [comment]
Hi @andreaswachowski, thanks for the issue!

I believe async/await are ES2017, meaning they should only parse if you set `ecmaVersion` to 8 in espree. ecmaVersion 7 implies ES2016, which does not have async/await in the spec.

**Comment by andreaswachowski** [comment]
I indeed (wrongly, apparently ;-)) assumed that `ecmaVersion=7` refers to ES2017. I confirm the test works fine with `ecmaVersion=8`. Thanks for the quick response!
