### ISSUE TITLE
Properties after an async method gets "Parsing error"

### ISSUE THREAD

**Issue by daltones** [eslint/espree#298]
ESLint: v3.6.1
ECMAVersion: 2017

This code:
```js
var foo = {
  async bar() {
    await 1;
  },
  baz: true
};
```

Outputs this:
```
<text>
  5:6  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)
```

The problem occurs just with regular properties declared after a async method.

It can be reproduced with:
```
echo 'var foo = {async bar(){await 1;}, baz: true};' | eslint --no-eslintrc --stdin --parser-options='ecmaVersion:2017'
```

**Comment by xjamundx** [comment]
Verified in `3.3.1`

```
> require('./espree.js').version
'3.3.1'
> require('./espree.js').parse('var foo = { async bar() { await 1}, baz: true }', { ecmaVersion: 8 })
SyntaxError: Unexpected token :
    at Parser.instance.raise.instance.raiseRecoverable (/Users/jamuferguson/dev/espree/espree.js:406:19)
    at Parser.instance.unexpected (/Users/jamuferguson/dev/espree/espree.js:439:14)
    at Parser.pp$3.parsePropertyValue (/Users/jamuferguson/dev/espree/node_modules/acorn/dist/acorn.js:2140:12)
    at Parser.instance.parseObj (/Users/jamuferguson/dev/espree/espree.js:389:18)
    at Parser.pp$3.parseExprAtom (/Users/jamuferguson/dev/espree/node_modules/acorn/dist/acorn.js:1930:19)
    at Parser.pp$3.parseExprSubscripts (/Users/jamuferguson/dev/espree/node_modules/acorn/dist/acorn.js:1817:21)
    at Parser.pp$3.parseMaybeUnary (/Users/jamuferguson/dev/espree/node_modules/acorn/dist/acorn.js:1794:19)
    at Parser.pp$3.parseExprOps (/Users/jamuferguson/dev/espree/node_modules/acorn/dist/acorn.js:1736:21)
    at Parser.pp$3.parseMaybeConditional (/Users/jamuferguson/dev/espree/node_modules/acorn/dist/acorn.js:1719:21)
    at Parser.pp$3.parseMaybeAssign (/Users/jamuferguson/dev/espree/node_modules/acorn/dist/acorn.js:1696:21)
> require('acorn').parse('var foo = { async bar() { await 1}, baz: true }', { ecmaVersion: 8 })
Node {
  type: 'Program',
  start: 0,
  end: 47,
  body: 
   [ Node {
       type: 'VariableDeclaration',
       start: 0,
       end: 47,
       declarations: [Object],
       kind: 'var' } ],
  sourceType: 'script' }
```

**Comment by xjamundx** [comment]
Also verified properties before work fine.

```
> require('./espree.js').parse('var foo = { eggs: true, async bar() { await 1 } }', { ecmaVersion: 8 })
Node {
```
