### ISSUE TITLE
Fails to parse export <ident> from syntax

### ISSUE THREAD

**Issue by nene** [eslint/espree#312]
Parsing the following fails:

```js
export foo from './foo';
```

Got the error with 3.2.0:

```js
/usr/local/lib/node_modules/lebab/node_modules/espree/espree.js:412
        throw err;
        ^

SyntaxError: Unexpected token foo
    at Parser.instance.raise.instance.raiseRecoverable (/usr/local/lib/node_modules/lebab/node_modules/espree/espree.js:408:19)
    at Parser.instance.unexpected (/usr/local/lib/node_modules/lebab/node_modules/espree/espree.js:441:14)
    at Parser.pp.expect (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:610:26)
    at Parser.pp$1.parseExportSpecifiers (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:1329:8)
    at Parser.pp$1.parseExport (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:1260:28)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:754:69)
    at Parser.pp$1.parseTopLevel (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:658:23)
    at Parser.parseTopLevel (/usr/local/lib/node_modules/lebab/node_modules/espree/espree.js:270:34)
    at Parser.parse (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:528:15)
    at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:3357:37)
```

But it also seems present in 3.3.2: http://astexplorer.net/#/HcsXwyydjG

It does however work with `export * from` and `export {} from`.

**Comment by not-an-aardvark** [comment]
Is this actually valid syntax? It doesn't seem to appear in [this table](https://tc39.github.io/ecma262/#table-42).

I think the correct code for that would be

```js
export {default as foo} from './foo';
```

**Comment by nene** [comment]
Frankly I'm not really sure. I've never used it. Just got a bug report highlighting that it doesn't work.

Apparently Babylon supports it, but they might be supporting some old version of the module syntax. Now that I inspect the AST of Babylon more closely I'm not really sure whether it should mean

    export {default as foo} from './foo';

or 

    export {foo as default} from './foo';

And the other parsers that seem to support it on the surface (flow, typescript) generate AST that doesn't make sense at all (like Flow sees three separate export specifiers).

**Comment by nene** [comment]
Ah, also now that I read the bug report more closely I see:

> If I want to apply some transformation to my source code files that contain syntax from **proposal stages**, I get exception for that files.

**Comment by btmills** [comment]
[Export default from](https://github.com/leebyron/ecmascript-export-default-from) is currently a [stage 1 proposal](https://github.com/tc39/proposals).

**Comment by nene** [comment]
Sorry for the confusion.
