### ISSUE TITLE
npm test fails with token const error.  Any idea on how in can resolve it?

### ISSUE THREAD

**Issue by visualjeff** [eslint/espree#320]
Node: 6.9.1
Hapi:  ^16.0.1
Lab:  ^11.2.1

Its been driving me nuts...  Anybody else run into this?

```
jeffg@debian:~/Documents/nodeHapiTemplate$ npm test

> nodeHapiTemplate@1.0.0 test /home/jeffg/Documents/nodeHapiTemplate
> ./node_modules/lab/bin/lab -c

/home/jeffg/Documents/nodeHapiTemplate/node_modules/espree/espree.js:443
        throw err;
        ^

SyntaxError: Unexpected token const
    at Parser.instance.raise.instance.raiseRecoverable (/home/jeffg/Documents/nodeHapiTemplate/node_modules/espree/espree.js:439:19)
    at Parser.instance.unexpected (/home/jeffg/Documents/nodeHapiTemplate/node_modules/espree/espree.js:472:14)
    at Parser.pp$2.parseBindingAtom (/home/jeffg/Documents/nodeHapiTemplate/node_modules/acorn/dist/acorn.js:1535:10)
    at Parser.pp$1.parseVarId (/home/jeffg/Documents/nodeHapiTemplate/node_modules/acorn/dist/acorn.js:1094:18)
    at Parser.pp$1.parseVar (/home/jeffg/Documents/nodeHapiTemplate/node_modules/acorn/dist/acorn.js:1077:12)
    at Parser.pp$1.parseVarStatement (/home/jeffg/Documents/nodeHapiTemplate/node_modules/acorn/dist/acorn.js:962:8)
    at Parser.pp$1.parseStatement (/home/jeffg/Documents/nodeHapiTemplate/node_modules/acorn/dist/acorn.js:741:17)
    at Parser.pp$1.parseTopLevel (/home/jeffg/Documents/nodeHapiTemplate/node_modules/acorn/dist/acorn.js:658:23)
    at Parser.parseTopLevel (/home/jeffg/Documents/nodeHapiTemplate/node_modules/espree/espree.js:301:34)
    at Parser.parse (/home/jeffg/Documents/nodeHapiTemplate/node_modules/acorn/dist/acorn.js:528:15)
    at Object.parse (/home/jeffg/Documents/nodeHapiTemplate/node_modules/acorn/dist/acorn.js:3357:37)
    at Object.parse (/home/jeffg/Documents/nodeHapiTemplate/node_modules/espree/espree.js:738:21)

```

Any tips or pointers would be appreciated.  Its just showed up after I blew away my node_modules directory and performed a fresh npm install.

Thanks,

Jeff

**Comment by platinumazure** [comment]
@visualjeff Hard to tell, but it looks like you're running `npm test` for a different project, not espree?

If that's the case, then you need to find where espree is being used in your project. When you call `espree.parse`, you should pass in an `ecmaVersion` option with a value of 6 or greater. That will hopefully fix your issue.

**Comment by visualjeff** [comment]
Yes, I'm building a hapi server.  I will grep the project and then the node modules to attempt to find where espree is being used.    I'll share my findings.  Thank you for the hint.

**Comment by visualjeff** [comment]
Its lab 11.2.2 that is using espree.

node_modules/lab/lib/coverage.js:36

I'm going to attempt to bring up the version of lab and test again.

**Comment by platinumazure** [comment]
@visualjeff So either the lab module does not support coverage for ES6 syntax, or the lab module will have configuration you can tweak to ensure it calls espree with ES6+ configuration.

In either case, this is likely not an espree issue, so I'm going to close the issue. Please reopen if you believe there's still an espree issue after your investigation. Thanks!

**Comment by visualjeff** [comment]
Think I found out what is causing the issue.

https://github.com/hapijs/lab/issues/668

**Comment by visualjeff** [comment]
Resolved.
