### ISSUE TITLE
Doesn't appear to support async functions?

### ISSUE THREAD

**Issue by gkovacs** [eslint/espree#322]
Here's my testcase, I've tested with both espree 3.4.0 and with master ( https://github.com/eslint/espree/commit/a3442b5949dd249e1a81ce4e014ca5e0f17f732c ). I'm on node.js 7.7.3 on macOS Sierra (10.12.2)

```javascript
var espree = require('espree')
var code = 'async function foo() {}'
console.log(espree.parse(code))
```

However this testcase says `unexpected token function` when parsing:

```
geza@gezamac ~/espree_test> node ./async_example.js
/Users/geza/espree_test/node_modules/espree/espree.js:443
        throw err;
        ^

SyntaxError: Unexpected token function
    at Parser.instance.raise.instance.raiseRecoverable (/Users/geza/espree_test/node_modules/espree/espree.js:439:19)
    at Parser.instance.unexpected (/Users/geza/espree_test/node_modules/espree/espree.js:472:14)
    at Parser.pp.semicolon (/Users/geza/espree_test/node_modules/acorn/dist/acorn.js:593:59)
    at Parser.pp$1.parseExpressionStatement (/Users/geza/espree_test/node_modules/acorn/dist/acorn.js:1011:8)
    at Parser.pp$1.parseTopLevel (/Users/geza/espree_test/node_modules/acorn/dist/acorn.js:658:23)
    at Object.parse (/Users/geza/espree_test/node_modules/espree/espree.js:738:21)
    at Object.<anonymous> (/Users/geza/espree_test/async_example.js:3:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

Same results if I add `--harmony-async-await` or `--harmony` to the node command.

**Comment by gkovacs** [comment]
Ah it appears I need to add `{ecmaVersion: 8}` to the parse options to make it correctly parse. Probably should add that to the documentation.
