### ISSUE TITLE
await in a non-async function lints to the following word

### ISSUE THREAD

**Issue by Nokel81** [eslint/espree#377]
Example source code:

```js
function (...)
{
    ...
    await fnReturnPromise(...);
    ...
}
```

The error produced points at `fnReturnPromise`

**Comment by Nokel81** [comment]
Example: 

`console.log(require('espree').parse('function name() { await foo; }', {ecmaVersion: 8, tokens: true}).tokens);`

```
SyntaxError: Unexpected token foo
    at Parser.instance.raise.instance.raiseRecoverable (/Users/sebastianmalton/repos/eslint/node_modules/espree/espree.js:417:19)
    at Parser.instance.unexpected (/Users/sebastianmalton/repos/eslint/node_modules/espree/espree.js:450:14)
    at Parser.pp.semicolon (/Users/sebastianmalton/repos/eslint/node_modules/acorn/dist/acorn.js:621:64)
    at Parser.pp$1.parseExpressionStatement (/Users/sebastianmalton/repos/eslint/node_modules/acorn/dist/acorn.js:1085:8)
    at Parser.pp$1.parseStatement (/Users/sebastianmalton/repos/eslint/node_modules/acorn/dist/acorn.js:815:24)
    at Parser.pp$1.parseBlock (/Users/sebastianmalton/repos/eslint/node_modules/acorn/dist/acorn.js:1104:23)
    at Parser.pp$3.parseFunctionBody (/Users/sebastianmalton/repos/eslint/node_modules/acorn/dist/acorn.js:2591:22)
    at Parser.pp$1.parseFunction (/Users/sebastianmalton/repos/eslint/node_modules/acorn/dist/acorn.js:1211:8)
    at Parser.pp$1.parseFunctionStatement (/Users/sebastianmalton/repos/eslint/node_modules/acorn/dist/acorn.js:921:15)
    at Parser.pp$1.parseStatement (/Users/sebastianmalton/repos/eslint/node_modules/acorn/dist/acorn.js:773:17)
```

**Comment by mysticatea** [comment]
This is working correctly.
`await` is an identifier reference when it's outside of `async` functions, then `await fnReturnPromise` is two consecutive identifier references, so `fnReturnPromise` is unexpected token.
