### ISSUE TITLE
Error: var err = new SyntaxError(message);

### ISSUE THREAD

**Issue by MatheusRV** [eslint/espree#413]
```
/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/javascript-obfuscator/node_modules/espree/espree.js:273
        var err = new SyntaxError(message);
                  ^
SyntaxError: Identifier directly after number
    at Parser.instance.raise.instance.raiseRecoverable (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/javascript-obfuscator/node_modules/espree/espree.js:273:19)
    at Parser.pp$8.readNumber (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/acorn/dist/acorn.js:5005:59)
    at Parser.pp$8.getTokenFromCode (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/acorn/dist/acorn.js:4870:17)
    at Parser.pp$8.readToken (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/acorn/dist/acorn.js:4628:15)
    at Parser.pp$8.nextToken (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/acorn/dist/acorn.js:4619:15)
    at Parser.pp$8.next (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/acorn/dist/acorn.js:4576:8)
    at Parser.next (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/javascript-obfuscator/node_modules/espree/espree.js:251:25)
    at Parser.pp$1.parseVarStatement (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/acorn/dist/acorn.js:1033:8)
    at Parser.pp$1.parseStatement (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/acorn/dist/acorn.js:788:17)
    at Parser.pp$1.parseTopLevel (/mnt/d/Cloud/GitHub/kodemaze/product/node_modules/acorn/dist/acorn.js:706:23)
```

```
 info it worked if it ends with ok
1 verbose cli [ '/home/turing/.nvm/versions/node/v8.15.1/bin/node',
1 verbose cli   '/home/turing/.nvm/versions/node/v8.15.1/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v8.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle KodeMaze@0.5.0~prebuild: KodeMaze@0.5.0
6 info lifecycle KodeMaze@0.5.0~build: KodeMaze@0.5.0
7 verbose lifecycle KodeMaze@0.5.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle KodeMaze@0.5.0~build: PATH: /home/turing/.nvm/versions/node/v8.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-$9 verbose lifecycle KodeMaze@0.5.0~build: CWD: /mnt/d/Cloud/GitHub/kodemaze/product
10 silly lifecycle KodeMaze@0.5.0~build: Args: [ '-c', 'gulp clean && gulp build && gulp polish' ]
11 silly lifecycle KodeMaze@0.5.0~build: Returned: code: 1  signal: null
12 info lifecycle KodeMaze@0.5.0~build: Failed to exec build script
13 verbose stack Error: KodeMaze@0.5.0 build: `gulp clean && gulp build && gulp polish`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/turing/.nvm/versions/node/v8.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/ind$13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/turing/.nvm/versions/node/v8.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib$13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid KodeMaze@0.5.0
15 verbose cwd /mnt/d/Cloud/GitHub/kodemaze/product
16 verbose Linux 4.4.0-17763-Microsoft
17 verbose argv "/home/turing/.nvm/versions/node/v8.15.1/bin/node" "/home/turing/.nvm/versions/node/v8.15.1/bin/npm" "run-script" "build"
18 verbose node v8.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE21 error errno 1
22 error KodeMaze@0.5.0 build: `gulp clean && gulp build && gulp polish`
22 error Exit status 123 error Failed at the KodeMaze@0.5.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

```
$ screenfetch
turing@DESKTOP-TKI46T0
OS: Ubuntu 18.04 bionic [Ubuntu on Windows 10]
Kernel: x86_64 Linux 4.4.0-17763-Microsoft
Uptime: 1h 4m
Packages: 702
Shell: bash 4.4.19
CPU: AMD FX-8320E Eight-Core @ 8x 3.2GHz
RAM: 3990MiB / 8175MiB
$ npm -v
6.4.1
$ nvm version
v8.15.1
```

**Comment by not-an-aardvark** [comment]
Hi, thanks for reporting an issue. Could you clarify what you were doing when this error appeared (preferably with the code that causes the issue)? Without more information, there's no way to tell whether this is an issue with your build process, an issue with espree, or something else.

**Comment by MatheusRV** [comment]
This error happens when I'm running a gulp script, it's not every time it happens, just sometimes and if I run the script again it can run without errors. I do not understand where the espree is in my project.

**Comment by not-an-aardvark** [comment]
Unfortunately, it's difficult to help or figure out what is going on without having more information about what the build script looks like.

To answer one of your questions, it seems like espree is used as a dependency of the `javascript-obfuscator` package, and the crash is occurring when espree is invoked by that package. Is your build script using that project?

**Comment by aladdin-add** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
