### ISSUE TITLE
Empty paren in expression throws TypeError

### ISSUE THREAD

**Issue by oaleynik** [eslint/espree#58]
The following example crashes eslint (caused by the last line in the file):

```
var left, aSize, bSize;

aSize = {
  width: 800,
  height: 600
};

bSize = {
  width: 200,
  height: 100
};

left = (aSize.width/2) - ()
```

with error

```
eslint test.js

/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/lib/token-store.js:181
            starts[right.range[0]] + padding
                              ^
TypeError: Cannot read property '0' of undefined
    at EventEmitter.api.getTokensBetween (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/lib/token-store.js:181:31)
    at RuleContext.(anonymous function) [as getTokensBetween] (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/lib/rule-context.js:82:33)
    at isSpaced (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/lib/rules/space-infix-ops.js:21:34)
    at EventEmitter.checkBinary (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/lib/rules/space-infix-ops.js:40:14)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/lib/eslint.js:673:25)
    at Controller.__execute (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/lib/eslint.js:666:24)
    at processFile (/home/julien/.nvm/v0.10.30/lib/node_modules/eslint/lib/cli-engine.js:172:27)
```

Looks like parentheses in the end of the line `left = (aSize.width / 2) - ()` treated as `ArrowParameterPlaceHolder` 

https://www.dropbox.com/s/0oltkd0vbdo0iew/Screenshot%202015-02-10%2018.51.52.png?dl=0

eslint/eslint#1816
AtomLinter/linter-eslint#28

**Comment by nzakas** [comment]
@xjamundx do you want to take a look at this?

**Comment by xjamundx** [comment]
Will totally check this out. Though here's what I'm seeing in Chrome with the same code:
![screen shot 2015-02-10 at 12 28 39 pm](https://cloud.githubusercontent.com/assets/246143/6135823/8d2d6b68-b120-11e4-940c-b5acb3366bc7.png)

Also some weird stuff here in the result:
http://esprima.org/demo/parse.html?code=left%20%3D%20(aSize.width%2F2)%20-%20()

I suppose the expected behavior is "not crash" though :)

**Comment by oaleynik** [comment]
@xjamundx if run eslint with `--rule {"arrowFunctions": false}` - it runs nicely, eslint reports `Unexpected token )` as expected

**Comment by xjamundx** [comment]
FYI this was solved in the destructuring PR

**Comment by xjamundx** [comment]
I'll write some tests to ensure it

**Comment by xjamundx** [comment]
When I set `config.parser` to the path of the `master` of `espree` and run eslint I see:
![screen shot 2015-02-10 at 1 48 05 pm](https://cloud.githubusercontent.com/assets/246143/6137161/85f01dea-b12b-11e4-9044-37e90db25a52.png)

**Comment by nzakas** [comment]
Ooh nice, thanks for the update.
