### ISSUE TITLE
Parser fails on generator methods

### ISSUE THREAD

**Issue by steadicat** [eslint/espree#85]
Espree parser fails on the following with `Unexpected token *`:

```javascript
class Foo {
  *bar() {
  }
}
```

Test case:

```javascript
var espree = require("espree");

espree.parse('class Foo {*bar() {}}', {
  "ecmaFeatures": {
    "classes": true,
    "generators": true,
    "objectLiteralShorthandMethods": true,
  },
});
```

Stack:

```
node_modules/espree/espree.js:5373
        throw e;
              ^
Error: Line 1: Unexpected token *
    at throwError (node_modules/espree/espree.js:2078:17)
    at throwUnexpected (node_modules/espree/espree.js:2141:5)
    at parseObjectPropertyKey (node_modules/espree/espree.js:2364:5)
    at parseClassBody (node_modules/espree/espree.js:4934:15)
    at parseClassDeclaration (node_modules/espree/espree.js:5023:17)
    at parseSourceElement (node_modules/espree/espree.js:5053:28)
    at parseSourceElements (node_modules/espree/espree.js:5101:25)
    at parseProgram (node_modules/espree/espree.js:5120:12)
    at Object.parse (node_modules/espree/espree.js:5361:19)
    at Object.<anonymous> (esp.js:3:8)
```

See eslint/eslint#1990.

**Comment by xjamundx** [comment]
If no one else does I can look at this tomorrow. Swore we tested for this....

**Comment by xjamundx** [comment]
Made some progress tonight. should have fix in the morning.
